[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2021"
name = "alarm-example"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
cfg-if = "1.0.0"
worker = { path = "../../worker", version = "0.0.12" }
