name = "alarm-example"
workers_dev = true
compatibility_date = "2022-09-12" # required
main = "./build/worker/shim.mjs"

[durable_objects]
bindings = [{ name = "ALARM", class_name = "AlarmObject" }]

[[migrations]]
tag = "v1"
new_classes = ["AlarmObject"]

[build]
command = "cargo install -q worker-build && worker-build --release"
